name: Create a comment on new PRs

on:
  push:
  pull_request:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump env context"
        run: echo '{{ env }}'
        shell: bash
      - name: "dump github context"
        run: echo '{{ github }}'
        shell: bash
